### ISSUE TITLE
crash on win32

### ISSUE THREAD

**Issue by abma** [tizbac/SpringMapConvNG#6]
for some reason on win32 build springmapconvng crashes on free():

https://github.com/tizbac/SpringMapConvNG/blob/a7ad2185be2394a8c150ef526157c4206246a162/TileStorage.cpp#L154

when commented out the free() calls it doesn't crash.... really strange. on linux it works fine.

compiled with visual studio, it crashes there, too, so no compiler bug.

if i add a
# include "IL/il_internal.h"

and repleace free with

ilfree()

it works...

no idea whats wrong :-/

ilCompressDXT is here:
https://github.com/LuaDist/libdevil/blob/master/src-IL/src/il_dds-save.c#L1249

surprisingly when run with wine it works fine...

**Comment by hoijui** [comment]
i don't get your confusion.
you allocate memory with an il_() function, and when using an il_() function to free that memory, it works fine...
that seems like a very clean solution to me. cleaner then using free(), and it fixes the bug; congrats! :-)
whatever special thing is done inside the il*() function that allocates, we should not care.
(i see that they use ialloc for example, no idea what it does specially, but as said, we should not worry about that)

**Comment by abma** [comment]
i'm not sure when/where #include "IL/il_internal.h" is available. it seems to be only available in the source-code package of DeviL. thats why i didn't made  a patch/pull-request.

and ops, i its "IL/devil_internal_exports.h"

**Comment by abma** [comment]
i made a workaround:

https://github.com/abma/SpringMapConvNG/commit/8b7c9150a2c91b8321ec675c67b133a8f92378ee

also i wrote a mail to one of the maintainers of devil, maybe he has an idea whats wrong.

**Comment by abma** [comment]
please use https://github.com/spring/SpringMapConvNG!

should be fixed there
